#cloud-config
# Set everything up
# NOT IN USE
groups:
  - minecraft

users:
  - default
  - name: minecraft
    gecos: minecraft
    shell: /bin/bash
    primary_group: minecraft

packages:
  - openjdk-17-jre-headless
  - unzip
  - make
  - gcc
  - libc6-dev
  - git

runcmd:
  - java -jar forge-1.20.1-47.1.28-installer.jar --installServer
  - git clone https://github.com/Tiiffi/mcrcon.git
  - cd mcrcon
  - make
  - sudo make install
